name: jaspr_bulma
description: jaspr components implementation for the bulma css framework
version: 0.0.1
repository: https://github.com/rubiktubik/jaspr_bulma

environment:
  sdk: ^3.5.1

dependencies:
  jaspr: ^0.16.0

dev_dependencies:
  jaspr_test: ^0.16.1
  lints: ^4.0.0
  test: ^1.24.0

topics:
  - jaspr
  - web
